"""Shared configuration field definitions for dashboard and runtime updates."""

from __future__ import annotations

from typing import Any, Dict, List


CONFIG_FIELDS: List[Dict[str, Any]] = [
    {"env": "PRODUCT_ID", "attr": "product_id", "type": "str"},
    {"env": "GRID_LINES", "attr": "grid_lines", "type": "int"},
    {"env": "GRID_BAND_PCT", "attr": "grid_band_pct", "type": "decimal"},
    {"env": "MIN_NOTIONAL_USD", "attr": "min_notional_usd", "type": "decimal"},
    {"env": "MIN_GRID_PROFIT_PCT", "attr": "min_grid_profit_pct", "type": "decimal"},
    {"env": "MAKER_FEE_PCT", "attr": "maker_fee_pct", "type": "decimal"},
    {"env": "TARGET_NET_PROFIT_PCT", "attr": "target_net_profit_pct", "type": "decimal"},
    {"env": "POLL_SECONDS", "attr": "poll_seconds", "type": "int"},
    {"env": "DYNAMIC_FEE_TRACKING_ENABLED", "attr": "dynamic_fee_tracking_enabled", "type": "bool"},
    {"env": "FEE_REFRESH_SECONDS", "attr": "fee_refresh_seconds", "type": "int"},
    {"env": "USE_EXCHANGE_BRACKET_ORDERS", "attr": "use_exchange_bracket_orders", "type": "bool"},
    {"env": "BRACKET_TAKE_PROFIT_PCT", "attr": "bracket_take_profit_pct", "type": "decimal"},
    {"env": "BRACKET_STOP_LOSS_PCT", "attr": "bracket_stop_loss_pct", "type": "decimal"},
    {"env": "GRID_SPACING_MODE", "attr": "grid_spacing_mode", "type": "str"},
    {"env": "ATR_ENABLED", "attr": "atr_enabled", "type": "bool"},
    {"env": "ATR_PERIOD", "attr": "atr_period", "type": "int"},
    {"env": "ATR_BAND_MULTIPLIER", "attr": "atr_band_multiplier", "type": "decimal"},
    {"env": "ATR_MIN_BAND_PCT", "attr": "atr_min_band_pct", "type": "decimal"},
    {"env": "ATR_MAX_BAND_PCT", "attr": "atr_max_band_pct", "type": "decimal"},
    {"env": "BASE_ORDER_NOTIONAL_USD", "attr": "base_order_notional_usd", "type": "decimal"},
    {"env": "QUOTE_RESERVE_PCT", "attr": "quote_reserve_pct", "type": "decimal"},
    {"env": "MAX_BTC_INVENTORY_PCT", "attr": "max_btc_inventory_pct", "type": "decimal"},
    {"env": "HARD_STOP_LOSS_PCT", "attr": "hard_stop_loss_pct", "type": "decimal"},
    {"env": "TREND_GRANULARITY", "attr": "trend_candle_granularity", "type": "str"},
    {"env": "TREND_CANDLE_LIMIT", "attr": "trend_candle_limit", "type": "int"},
    {"env": "TREND_EMA_FAST", "attr": "trend_ema_fast", "type": "int"},
    {"env": "TREND_EMA_SLOW", "attr": "trend_ema_slow", "type": "int"},
    {"env": "TREND_STRENGTH_THRESHOLD", "attr": "trend_strength_threshold", "type": "decimal"},
    {"env": "DYNAMIC_INVENTORY_CAP_ENABLED", "attr": "dynamic_inventory_cap_enabled", "type": "bool"},
    {"env": "INVENTORY_CAP_MIN_PCT", "attr": "inventory_cap_min_pct", "type": "decimal"},
    {"env": "INVENTORY_CAP_MAX_PCT", "attr": "inventory_cap_max_pct", "type": "decimal"},
    {"env": "PAPER_TRADING_MODE", "attr": "paper_trading_mode", "type": "bool"},
    {"env": "PAPER_START_USD", "attr": "paper_start_usd", "type": "decimal"},
    {"env": "PAPER_START_BTC", "attr": "paper_start_btc", "type": "decimal"},
    {"env": "PAPER_FILL_EXCEED_PCT", "attr": "paper_fill_exceed_pct", "type": "decimal"},
    {"env": "PAPER_FILL_DELAY_SECONDS", "attr": "paper_fill_delay_seconds", "type": "int"},
    {"env": "PAPER_SLIPPAGE_PCT", "attr": "paper_slippage_pct", "type": "decimal"},
    {"env": "DASHBOARD_ENABLED", "attr": "dashboard_enabled", "type": "bool"},
    {"env": "DASHBOARD_HOST", "attr": "dashboard_host", "type": "str"},
    {"env": "DASHBOARD_PORT", "attr": "dashboard_port", "type": "int"},
    {"env": "TRAILING_GRID_ENABLED", "attr": "trailing_grid_enabled", "type": "bool"},
    {"env": "TRAILING_TRIGGER_LEVELS", "attr": "trailing_trigger_levels", "type": "int"},
    {"env": "STATE_DB_PATH", "attr": "state_db_path", "type": "str"},
    {"env": "LEGACY_ORDERS_JSON_ENABLED", "attr": "legacy_orders_json_enabled", "type": "bool"},
    {"env": "SAFE_START_ENABLED", "attr": "safe_start_enabled", "type": "bool"},
    {"env": "BASE_BUY_MODE", "attr": "base_buy_mode", "type": "str"},
]
